steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'pods']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-gke-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'secrets', '--namespace=default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-gke-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['describe', 'secrets/db-user-pass', '--namespace=default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-gke-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['delete', 'secrets/db-user-pass', '--namespace=default']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-gke-cluster'
